// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/proto/calling/v1/calling.proto

package callingv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

type CreateCallSessionRequest struct {
	CallerId         string `protobuf:"bytes,1,opt,name=caller_id,json=callerId,proto3" json:"caller_id,omitempty"`
	ReceiverId       string `protobuf:"bytes,2,opt,name=receiver_id,json=receiverId,proto3" json:"receiver_id,omitempty"`
	CallType         string `protobuf:"bytes,3,opt,name=call_type,json=callType,proto3" json:"call_type,omitempty"`
	DurationLimitSec int32  `protobuf:"varint,4,opt,name=duration_limit_sec,json=durationLimitSec,proto3" json:"duration_limit_sec,omitempty"`
}

type CreateCallSessionResponse struct {
	RoomId        string `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	CallerToken   string `protobuf:"bytes,2,opt,name=caller_token,json=callerToken,proto3" json:"caller_token,omitempty"`
	ReceiverToken string `protobuf:"bytes,3,opt,name=receiver_token,json=receiverToken,proto3" json:"receiver_token,omitempty"`
	LivekitUrl    string `protobuf:"bytes,4,opt,name=livekit_url,json=livekitUrl,proto3" json:"livekit_url,omitempty"`
	CreatedAt     int64  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

type EndCallSessionRequest struct {
	RoomId      string `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	RequestedBy string `protobuf:"bytes,2,opt,name=requested_by,json=requestedBy,proto3" json:"requested_by,omitempty"`
}

type EndCallSessionResponse struct {
	Success bool  `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	EndedAt int64 `protobuf:"varint,2,opt,name=ended_at,json=endedAt,proto3" json:"ended_at,omitempty"`
}

type GetCallSessionStatusRequest struct {
	RoomId string `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
}

type GetCallSessionStatusResponse struct {
	RoomId             string   `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Status             string   `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	ActiveParticipants []string `protobuf:"bytes,3,rep,name=active_participants,json=activeParticipants,proto3" json:"active_participants,omitempty"`
	DurationSec        int64    `protobuf:"varint,4,opt,name=duration_sec,json=durationSec,proto3" json:"duration_sec,omitempty"`
}

// CallingServiceClient is the client API for CallingService service.
type CallingServiceClient interface {
	CreateCallSession(ctx context.Context, in *CreateCallSessionRequest, opts ...grpc.CallOption) (*CreateCallSessionResponse, error)
	EndCallSession(ctx context.Context, in *EndCallSessionRequest, opts ...grpc.CallOption) (*EndCallSessionResponse, error)
	GetCallSessionStatus(ctx context.Context, in *GetCallSessionStatusRequest, opts ...grpc.CallOption) (*GetCallSessionStatusResponse, error)
}

type callingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCallingServiceClient(cc grpc.ClientConnInterface) CallingServiceClient {
	return &callingServiceClient{cc}
}

func (c *callingServiceClient) CreateCallSession(ctx context.Context, in *CreateCallSessionRequest, opts ...grpc.CallOption) (*CreateCallSessionResponse, error) {
	out := new(CreateCallSessionResponse)
	err := c.cc.Invoke(ctx, "/calling.v1.CallingService/CreateCallSession", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *callingServiceClient) EndCallSession(ctx context.Context, in *EndCallSessionRequest, opts ...grpc.CallOption) (*EndCallSessionResponse, error) {
	out := new(EndCallSessionResponse)
	err := c.cc.Invoke(ctx, "/calling.v1.CallingService/EndCallSession", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *callingServiceClient) GetCallSessionStatus(ctx context.Context, in *GetCallSessionStatusRequest, opts ...grpc.CallOption) (*GetCallSessionStatusResponse, error) {
	out := new(GetCallSessionStatusResponse)
	err := c.cc.Invoke(ctx, "/calling.v1.CallingService/GetCallSessionStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CallingServiceServer is the server API for CallingService service.
type CallingServiceServer interface {
	CreateCallSession(context.Context, *CreateCallSessionRequest) (*CreateCallSessionResponse, error)
	EndCallSession(context.Context, *EndCallSessionRequest) (*EndCallSessionResponse, error)
	GetCallSessionStatus(context.Context, *GetCallSessionStatusRequest) (*GetCallSessionStatusResponse, error)
}

// UnimplementedCallingServiceServer can be embedded to have forward compatible implementations.
type UnimplementedCallingServiceServer struct{}

func (*UnimplementedCallingServiceServer) CreateCallSession(context.Context, *CreateCallSessionRequest) (*CreateCallSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCallSession not implemented")
}
func (*UnimplementedCallingServiceServer) EndCallSession(context.Context, *EndCallSessionRequest) (*EndCallSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EndCallSession not implemented")
}
func (*UnimplementedCallingServiceServer) GetCallSessionStatus(context.Context, *GetCallSessionStatusRequest) (*GetCallSessionStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCallSessionStatus not implemented")
}

func RegisterCallingServiceServer(s *grpc.Server, srv CallingServiceServer) {
	s.RegisterService(&_CallingService_serviceDesc, srv)
}

func _CallingService_CreateCallSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCallSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CallingServiceServer).CreateCallSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calling.v1.CallingService/CreateCallSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CallingServiceServer).CreateCallSession(ctx, req.(*CreateCallSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CallingService_EndCallSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EndCallSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CallingServiceServer).EndCallSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calling.v1.CallingService/EndCallSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CallingServiceServer).EndCallSession(ctx, req.(*EndCallSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CallingService_GetCallSessionStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCallSessionStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CallingServiceServer).GetCallSessionStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calling.v1.CallingService/GetCallSessionStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CallingServiceServer).GetCallSessionStatus(ctx, req.(*GetCallSessionStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CallingService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "calling.v1.CallingService",
	HandlerType: (*CallingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCallSession",
			Handler:    _CallingService_CreateCallSession_Handler,
		},
		{
			MethodName: "EndCallSession",
			Handler:    _CallingService_EndCallSession_Handler,
		},
		{
			MethodName: "GetCallSessionStatus",
			Handler:    _CallingService_GetCallSessionStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/calling/v1/calling.proto",
}
